### ISSUE TITLE
How to use Masonry

### ISSUE THREAD

**Issue by edsonmartins** [colepatrickturner/react-components#1]
Good Morning
I read your article "Masonry in React: A Performance Hell" and I'm trying to use the components but I'm not getting it because it seems like some dependencies are missing. Do you have any examples using Masonry to help me?

Edson Martins
Brasil

**Comment by coleturner** [comment]
Hey @edsonmartins 

Everything _should_ be in order in the comments, if you find something is missing or doesn't feel quite right feel free to share any errors or codepens you have that can help clarify.

An example can be found @ thehunt.com

https://github.com/colepatrickturner/react-components/blob/master/Masonry/View.jsx#L22
