### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isRequired' of undefined at Masonry.jsx (Masonry.jsx:88)

### ISSUE THREAD

**Issue by famigone** [colepatrickturner/react-components#3]
Hi Patrick! I had copy and paste "View.jsx" in my project. Then install _meteor npm install --save classnames lodash.throttle_

Then, i import the component and get that error: **Uncaught TypeError: Cannot read property 'isRequired' of undefined at Masonry.jsx (Masonry.jsx:88)**

**Comment by artndes9** [comment]
change it to `PropTypes.func.isRequired`
