### ISSUE TITLE
Masonry columnGap filtering

### ISSUE THREAD

**Issue by glensomerville** [colepatrickturner/react-components#8]
Hi! Thanks for the write up and great component!

I'm in the process of converting this into TypeScript for a project where I'll be using it. Perhaps I don't quite understand the code, but it seems there's a possible bug on the following line and the line below it:

https://github.com/coleturner/react-components/blob/3ed900f93db64e2bd01aa9a98637fbec45ff9f88/Masonry/View.jsx#L258

As I understand, `columnGap` is of type `number[][]`, so for example `[[0, 1], [2, 4]]`. However in the above line the `filter` method is applied to the inner array here `columnGaps[item.column + index].filter(...)` and so it is traversing the number values of `columnGap` at a specific index. Therefore the array destructuring on the next line is invalid: `const [gapTop, gapHeight] = gap;`, since `gap` here is of type `number`, not `Array`.

**Comment by glensomerville** [comment]
Nevermind, my bad. There is one more level of nesting in there...

**Comment by coleturner** [comment]
@glensomerville for what it's worth - this component is not perfect either. [I've written it once again over while putting on a presentation for React Boston 2018](https://github.com/coleturner/react-boston-2018/blob/master/presentation/components/masonry.js) and had equally mixed results getting gap filling working with a different placement technique. 

If you don't need multi-column item spanning then I recommend column layouts with Flexbox. Cheers!
